### ISSUE TITLE
Redacted recommendations are very bright when using dark theme

### ISSUE THREAD

**Issue by bmos** [peabrainiac/youtube-recommendation-blocker#2]
Perhaps you can use the color YouTube has defined for the already-subscribed "subscribe" button?
I haven't looked at your code (I don't know much about web development), so perhaps you are already doing this and they have another name for that element in dark mode. Anyway, the real suggestion here is just having less contrast in dark mode.

It also makes it harder to tell which of the recommended videos were from the same channel.

Dark-theme example:
<img src="https://i.imgur.com/APR6el1.jpg" alt="example of appearance with dark theme" width="400">

Versus light-theme:
<img src="https://i.imgur.com/BZ5Y9TV.jpg" alt="example of appearance with light theme" width="400">

**Comment by peabrainiac** [comment]
The colors are already fully customizable in the addon settings (found by going to about `about:addons`, clicking the three dots next to the addon and then selecting options). You can edit the default colors there as you see fit, as well as add more colors to some specific channels, as seen here:

![grafik](https://user-images.githubusercontent.com/43812953/101182158-0a1db480-364e-11eb-9d12-8b8ca46b19c8.png)


If you find yourself switching between the dark and light theme very often, that is indeed a use case that I have so far not really  considered. You might be able to find colors that look well with both themes by choosing mostly dark gray colors and adding a lot oft transparency to then, like `#80808020` or `#80808030`.

The way this works is currently not really communicated in the settings, so that is something that might actually need some improvements - I'm not much of a ui designer though and also currently quite busy with some other things, so I don't see that happening anytime soon.
